export const surpriseMePrompts = [
  'an armchair in the shape of an avocado',
  'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
  'teddy bears shopping for groceries in Japan, ukiyo-e',
  'an oil painting by Matisse of a humanoid robot playing chess',
  'panda mad scientist mixing sparkling chemicals, digital art',
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
  'an astronaut lounging in a tropical resort in space, vaporwave',
  'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
  'a stained glass window depicting a hamburger and french fries',
  'a pencil and watercolor drawing of a bright city in the future with flying cars',
  'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
  'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  'an oil pastel drawing of an annoyed cat in a spaceship',
  'a painting of a fox in the style of Starry Night',
  'a bowl of soup that looks like a monster, knitted out of wool',
  'A plush toy robot sitting against a yellow wall',
  'A synthwave style sunset above the reflecting water of the sea, digital art',
  'Two futuristic towers with a skybridge covered in lush foliage, digital art',
  'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
  'A comic book cover of a superhero wearing headphones',
  'A centered explosion of colorful powder on a black background',
  'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
  'A photo of a white fur monster standing in a purple room',
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  'A Samurai riding a Horse on Mars, lomography.',
  'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
  'A realistic photograph of a young woman with blue eyes and blonde hair',
  'A man standing in front of a stargate to another dimension',
  'Spongebob Squarepants in the Blair Witch Project',
  'A velociraptor working at a hotdog stand, lomography',
  'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
  'A BBQ that is alive, in the style of a Pixar animated movie',
  'A futuristic cyborg dance club, neon lights',
  'The long-lost Star Wars 1990 Japanese Anime',
  'A hamburger in the shape of a Rubik’s cube, professional food photography',
  'A Synthwave Hedgehog, Blade Runner Cyberpunk',
  'An astronaut encountering an alien life form on a distant planet, photography',
  'A Dinosaur exploring Cape Town, photography',
  'A Man falling in Love with his Computer, digital art',
  'A photograph of a cyborg exploring Tokyo at night, lomography',
  'Dracula walking down the street of New York City in the 1920s, black and white photography',
  'Synthwave aeroplane',
  'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
  'A Space Shuttle flying above Cape Town, digital art',
  'A floating island made entirely of pancakes, syrup waterfall included, digital art.',
  'A steampunk-themed coffee shop with baristas wearing jetpacks, 3D render.',
  'A time-traveling T-Rex attempting to take a selfie with a vintage camera, photography.',
  'A group of penguins enjoying a disco party under the Northern Lights, digital art.',
  'Vincent van Gogh\'s "Starry Night" reimagined as a dessert buffet, pastry art.',
  'A cybernetic squirrel with LED-lit eyes collecting data in a futuristic park, digital art.',
  'An octopus playing a grand piano underwater with a jellyfish audience, watercolor painting.',
  'A panda riding a skateboard down a rainbow-colored staircase, graffiti-style art.',
  'A mermaid reading a holographic book in an underwater library, digital painting.',
  'A mosaic portrait of Einstein made entirely of puzzle pieces, mixed media art.',
  'A time-traveling phone booth with historical figures waiting in line, comic-style illustration.',
  'A hummingbird delivering mail in a steampunk world, mechanical wings and all, digital art.',
  'A wizard dueling with a dragon in a chess match atop a castle, oil painting.',
  'A futuristic cityscape where buildings are made of candy and chocolate, digital art.',
  'A squirrel ninja sneaking through a bonsai forest, capturing the art of stealth in photography.',
  'A group of elephants riding unicycles in a circus parade, watercolor painting.',
  'A Victorian-era lady walking her pet robotic dinosaur in a park, digital art.',
  'An astronaut surfing on a comet\'s tail in the depths of space, digital painting.',
  'A floating hot air balloon market in the clouds, bustling with fantastical vendors, 3D render.',
  'A time-traveling bookshelf with shelves from different historical eras, surreal collage.'
];